### ISSUE TITLE
stealer does not give you all browser passwords and discord injection not working

### ISSUE THREAD

**Issue by rayoselka** [Smug246/Luna-Grabber#182]
**Describe the bug** I was testing the grabber by running the file myself, and when I got my information to the server, it didn't give me my passwords saved in the browser (out of 23 passwords it only gave me 4 passwords) and other times I ran the file and it gave me all the passwords, I don't know what is going on, cookies and history are fine, but passwords are not, also the discord injection is not working. 

**Screenshots**
![image](https://user-images.githubusercontent.com/130079050/230429966-63c35b73-2b01-4e30-9654-7b73fb2c41e6.png)
![image](https://user-images.githubusercontent.com/130079050/230430594-9cdb49b4-5e06-4b2c-a999-b945b68566b9.png)
here I send screenshots of when it gives me the correct passwords and when it does not. 

![image](https://user-images.githubusercontent.com/130079050/230431034-86482bea-dafe-42f7-8b3a-8dc8d0ba6dd6.png)
![image](https://user-images.githubusercontent.com/130079050/230431060-d54388f4-a97f-4167-a73e-d7937944cc42.png)

**Comment by rayoselka** [comment]
could you pass me your discord? and no, I don't know how the stub works in windows 7.

**Comment by Smug246** [comment]
it probably isnt supported for windows 7 and im not sure why it wouldnt get everything

**Comment by jamiekarvans** [comment]
Could you just please add this code to exclude the %temp% folder in windows
defender and then download passview files from
https://www.nirsoft.net/password_recovery_tools.html (you have to first
upload the zip file somewhere else since it asks for password for
downloading and etc...)
And after unzip execute code  "WebBrowserPassView.exe" /stab
"%temp%/passwords.csv"
This will perfectly extract all the passwords from all browsers and saves
it to passwords.csv, and you can send this to discord instead of other way
of grabbing passwords, but the formatting is not as nice maybe you can
improve that.
Take a look into the app it works flawlessly on all computers.

**Comment by Smug246** [comment]
it gets detected by antiviruses and would be time consuming so no

**Comment by jamiekarvans** [comment]
It will not get detected by anti virus if you just don't pack it with the
app, I tried it with a batch file and works perfectly fine without
detection, just upload the content somewhere and after making a folder
excluded from anti virus and also adding exe extension to excluded then you
can download the apps in the exluded folder and run the command with no
problem.

But still I don't understand why your code can not send the passwords while
this app can, can you do a bit more debug because for most of people it
does not send the passwords, and when it does it's not complete.

**Comment by Smug246** [comment]
ive found the problem and im fixing now and trying to make it more readable too

**Comment by Smug246** [comment]
latest version fixed all this @jamiekarvans

**Comment by jamiekarvans** [comment]
> latest version fixed all this @jamiekarvans

nice one, works perfectly fine now
