### ISSUE TITLE
Bug: Functions such as "Anti Spam", "2FA Codes" and "WIFI Info" doesn't work

### ISSUE THREAD

**Issue by ag1lebyte** [Smug246/Luna-Grabber#732]
### What Did You Expect To Happen?

This info had to be collected and sent to a web hook

### What Happened?

I don't see that information in the messages the bot sends me

### Add Screenshots

Nothing to send

### Which Options Did You Select?

Wifi Info, 2FA Codes, Anti Spam

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by ag1lebyte** [comment]
I also wanted to ask about the ability to collect clipboard history. At the moment this feature cannot provide potentially valuable information, as it sends you the text that the user copied last

**Comment by Smug246** [comment]
anti spam doesn't grab any info it stops people from spamming you if there on a vm or rate limiting your webhook. wifi only grabs the passwords if you are currently using wifi on that device. it doesn't work for example ethernet. backup codes is a bit useless right now tbh because it searches for a single file in your downloads folder it doesn't have much of a search. maybe i can add a regex and improve it. lastly clipboard history isn't actually stored as persistent data on a windows machine. so that's why you can only get the most recent text copied. if you find a technique to somehow get the whole history i'd be more than happy to implement it.

**Comment by ag1lebyte** [comment]
I'm using WIFI on my laptop and the script doesn't grab passwords

**Comment by Smug246** [comment]
what laptop and windows version are you using because i just tested wifi stealing and it works fine

**Comment by Smug246** [comment]
also just tested self destruct and it works fine. are you getting any errors?

**Comment by ag1lebyte** [comment]
Self destruct doesn't work on (on a laptop will prolly produce the same result; I'm not getting any errors):
OS: Microsoft Windows 11 Pro             OS Build: 10.0.22621.2506              OS Version: 23H2


Wifi Info doesn't work on:
OS: Windows 10 Pro                             OS Build: 10.0.19041.3636              OS Version: 22H2
Manufacturer: LENOVO                         Model: 82HL

**Comment by Smug246** [comment]
type 'netsh wlan show profiles' in command prompt then press enter and ss what comes up

**Comment by ag1lebyte** [comment]
C:\WINDOWS\system32>netsh wlan show profiles

Profiles on interface Wi-Fi:

Group policy profiles (read only)
------------------------------------------
    <None>

User profiles
--------------
    All User Profile     : ASUS
    All User Profile     : Lincoln_5G
    All User Profile     : Lincoln
    All User Profile     : Home-60-5G
    All User Profile     : Home-60

**Comment by Smug246** [comment]
which one of those is the network ur using

**Comment by ag1lebyte** [comment]
Lincoln_5G

**Comment by Smug246** [comment]
type 'netsh wlan show profile Lincoln_5G key=clear' and show me what it says

**Comment by ag1lebyte** [comment]
One of the parameters that was in there was the password.
Wait... It may not work because the Windows license on my laptop only supports one interface language, and that's Russian?

**Comment by Smug246** [comment]
ye that would be it maybe

**Comment by ag1lebyte** [comment]
What build option r u using if self-destruct is working?

**Comment by Serpensin** [comment]
I'm working on WiFi, which is already fixed (not PSUHED yet).
It's actually possible, to grab the entire ClipboardHistory, as long as the user has this feature enabled. But that would require a special binary (written in C), that gets included. But since we don't want to add a compiled file to OSS, this will not happen.
