### ISSUE TITLE
Will You Decrease Detections

### ISSUE THREAD

**Issue by Luna122342** [Smug246/Luna-Grabber#740]
### What Did You Expect To Happen?

how do i make pyinstaller exe undected

### What Happened?

how do i make pyinstaller exe undected

### Add Screenshots

![OIP](https://github.com/Smug246/Luna-Grabber/assets/169272938/c389b5b6-d8cb-478c-9258-f7eae1c2b292)

### Which Options Did You Select?

System Info, 2FA Codes, Browser Info

### Check the following before submitting (If Applicable)

- [X] I have checked the existing [issues](https://github.com/Smug246/Luna-Grabber/issues)
- [X] I have followed the [installation](https://github.com/Smug246/Luna-Grabber?tab=readme-ov-file#installation) steps
- [X] I have attempted to resolve my problem by myself

**Comment by Smug246** [comment]
there's no simple way to do this. there's lots of evasion techniques that you could integrate but it's a lot of effort for a grabber made in python. another reason this project could never be fud is because so many people would upload it to virus total and the detections would rapidly increase. i havnt actually seen a completely fud python grabber compiled with pyinstaller. this is mainly because anti viruses will just flag pyinstaller signature 99% of the time even if it isn't a virus. if your really looking for fud malware. you'd need to create your own unique techniques in languages such as c, c++, rust or golang.
